source 'https://rubygems.org'

gem 'rspec', '2.14.1'
gem 'capybara'
gem 'selenium-webdriver'
gem 'poltergeist'
gem 'initializer'
gem 'require_all'
gem 'ruby_version'
gem 'virtus'
gem 'test_abstractions'
